#pragma once
#include "core/result.hh"
#include "sdk/node.hh"
#include "sdk/types.hh"
#include <concepts>
#include <span>
#include <string>
#include <type_traits>
#include <utility>

template <typename Type>
struct LuaTraits
{};

template <typename>
struct MemberPointerTraits;

template <typename Class, typename Member>
struct MemberPointerTraits<Member Class::*>
{
  using class_type  = Class;
  using member_type = Member;
};

template <typename Type>
using LuaTranslator = Status (*)(LuaNode const&, LuaKey const&, Type&);

// A field erases its member type behind one callback. The callback generated by lua_field still
// knows the exact pointer-to-member type and can therefore dispatch to primitive or table
// translation without adding that member type to a variant.
template <typename Type>
struct LuaField
{
  LuaKey          key;
  LuaTranslator<Type> translate;
};

template <typename Type>
using LuaSchema = std::span<LuaField<Type> const>;

template <typename Type>
concept LuaTable = requires {
  { LuaTraits<Type>::schema } -> std::convertible_to<LuaSchema<Type>>;
};

template <typename Type>
concept LuaValue = std::same_as<Type, bool> || std::integral<Type> || std::floating_point<Type>
                || std::same_as<Type, std::string>;

template <LuaValue Type>
Status translate(LuaNode const& node, Type& out);

template <LuaTable Type>
Status translate(LuaNode const& node, Type& out);

template <auto Member>
constexpr auto lua_field(LuaKey key)
{
  using MemberPointer = decltype(Member);
  using Class         = typename MemberPointerTraits<MemberPointer>::class_type;

  return LuaField<Class>{
    .key = std::move(key),
    .translate = [](LuaNode const& node, LuaKey const& field, Class& out) {
      Result<LuaNode> value = node.find(field);
      if (!value) return Status(Error(std::move(value).error()));
      return translate(*value, out.*Member);
    },
  };
}

template <LuaValue Type>
Status translate(LuaNode const& node, Type& out)
{
  Result<Type> value = node.expect<Type>();
  if (!value) return Error(std::move(value).error());
  out = std::move(*value);
  return {};
}

template <LuaTable Type>
Status translate(LuaNode const& node, Type& out)
{
  if (node.type() != LuaType::Table) {
    return Error(
      describe(node) + ": expected table but found " + std::string(describe(node.type())));
  }

  for (LuaField<Type> const& field : LuaTraits<Type>::schema) {
    Status result = field.translate(node, field.key, out);
    if (!result) return result;
  }
  return {};
}

template <typename Type>
requires std::default_initializable<Type> && (LuaValue<Type> || LuaTable<Type>)
[[nodiscard]] Result<Type> translate(LuaNode const& node)
{
  Type   out{};
  Status result = translate(node, out);
  if (!result) return Error(std::move(result).error());
  return out;
}
