name: Check Format
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cc'
      - '**.hh'
  push:
    branches: [ main ]
    paths:
      - '**.cc'
      - '**.hh'
jobs:
  format:
    runs-on: ubuntu-latest
    container: fedora:43
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: dnf install -y clang-tools-extra
      - name: Check Formatting
        run: clang-format --version && find . -name '*.cc' -o -name '*.hh' | xargs clang-format --dry-run --Werror

