name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cc'
      - '**.hh'
      - '**/CMakeLists.txt'
  push:
    branches: [ main ]
    paths:
      - '**.cc'
      - '**.hh'
      - '**/CMakeLists.txt'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: fedora:43
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        dnf install -y \
          clang clang-tools-extra cmake ninja-build catch catch-devel \
          lua lua-devel glm-devel SDL3 SDL3-devel
    - name: Configure
      run: cmake --preset clang-debug -DBUILD_TESTS=ON -DENABLE_LINTER=ON
    - name: Build
      run: cmake --build --preset clang-debug
    - name: Run Tests
      run: ctest --preset clang-debug --output-on-failure

